# Generated by Django 5.0.6 on 2024-05-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_studygoal_user_studylog_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygoal',
            name='target_minutes',
            field=models.IntegerField(),
        ),
    ]
